/**
 * Generate data files (lib/constants.ts, lib/services.ts, etc.)
 */

import type { SiteConfig, GeneratedFile } from '@siteforge/shared';

export function generateDataFiles(siteConfig: SiteConfig): GeneratedFile[] {
  return [
    generateConstants(siteConfig),
    generateServices(siteConfig),
    generateCities(siteConfig),
    generateUtils(),
  ];
}

function generateConstants(siteConfig: SiteConfig): GeneratedFile {
  const content = `/**
 * Site configuration
 * Generated by SiteForge
 */

export const SITE_CONFIG = {
  name: "${siteConfig.name}",
  legalName: "${siteConfig.legalName}",
  domain: "${siteConfig.domain}",
  tagline: "${siteConfig.tagline.replace(/"/g, '\\"')}",
  description: "${siteConfig.description.replace(/"/g, '\\"')}",

  // Contact
  phone: "${siteConfig.phone}",
  phoneDisplay: "${siteConfig.phoneDisplay}",
  phoneLink: "${siteConfig.phoneLink}",
  email: "${siteConfig.email}",

  // Primary Address
  address: {
    city: "${siteConfig.primaryAddress.city}",
    state: "${siteConfig.primaryAddress.state}",
    stateAbbr: "${siteConfig.primaryAddress.stateAbbr}",
    zip: "${siteConfig.primaryAddress.zip}",
    full: "${siteConfig.primaryAddress.full}",
    formatted: "${siteConfig.primaryAddress.formatted}",
  },

  // Hours
  hours: {
    weekdays: "${siteConfig.hours.weekdays}",
    saturday: "${siteConfig.hours.saturday}",
    sunday: "${siteConfig.hours.sunday}",
    emergency: ${siteConfig.hours.emergency},
  },

  // Social
  social: {
    ${Object.entries(siteConfig.social || {})
      .filter(([_, v]) => v)
      .map(([k, v]) => `${k}: "${v}"`)
      .join(',\n    ')}
  },

  // Rating
  rating: {
    value: ${siteConfig.rating.value},
    count: ${siteConfig.rating.count},
    source: "${siteConfig.rating.source}",
    display: "${siteConfig.rating.display}",
  },

  // Credentials
  yearsInBusiness: ${siteConfig.yearsInBusiness},
  certifications: ${JSON.stringify(siteConfig.certifications)},
  licenses: ${JSON.stringify(siteConfig.licenses)},
  insurance: ${JSON.stringify(siteConfig.insurance)},

  // Industry
  industry: "${siteConfig.industry}",
  industryDisplay: "${siteConfig.industryDisplay}",

  // SEO
  seo: {
    titleTemplate: "${siteConfig.seo.titleTemplate}",
    defaultTitle: "${siteConfig.seo.defaultTitle.replace(/"/g, '\\"')}",
    defaultDescription: "${siteConfig.seo.defaultDescription.replace(/"/g, '\\"')}",
    keywords: ${JSON.stringify(siteConfig.seo.keywords)},
    canonicalBase: "${siteConfig.seo.canonicalBase}",
  },
} as const;

export const VALUE_PROPS = ${JSON.stringify(siteConfig.valueProps, null, 2)} as const;

export type SiteConfig = typeof SITE_CONFIG;
`;

  return {
    path: 'src/lib/constants.ts',
    content,
    type: 'data',
    generator: 'template',
    size: 0,
  };
}

function generateServices(siteConfig: SiteConfig): GeneratedFile {
  const content = `/**
 * Services data
 * Generated by SiteForge
 */

export interface Service {
  title: string;
  shortTitle: string;
  slug: string;
  description: string;
  shortDescription: string;
  features: string[];
  benefits: string[];
  icon: string;
  keywords: string[];
  metaTitle: string;
  metaDescription: string;
}

export const SERVICES: Service[] = ${JSON.stringify(siteConfig.services, null, 2)};

export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((service) => service.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return SERVICES.map((service) => service.slug);
}
`;

  return {
    path: 'src/lib/services.ts',
    content,
    type: 'data',
    generator: 'template',
    size: 0,
  };
}

function generateCities(siteConfig: SiteConfig): GeneratedFile {
  const content = `/**
 * Cities/locations data
 * Generated by SiteForge
 */

export interface City {
  name: string;
  state: string;
  stateAbbr: string;
  slug: string;
  priority: "high" | "medium" | "low";
  county?: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  primaryKeyword: string;
  nearbyAreas: string[];
  neighborhoods: string[];
}

export const CITIES: City[] = ${JSON.stringify(siteConfig.cities, null, 2)};

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((city) => city.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return CITIES.map((city) => city.slug);
}

export const PRIMARY_CITY = CITIES[0];
`;

  return {
    path: 'src/lib/cities.ts',
    content,
    type: 'data',
    generator: 'template',
    size: 0,
  };
}

function generateUtils(): GeneratedFile {
  const content = `/**
 * Utility functions
 * Generated by SiteForge
 */

import { clsx, type ClassValue } from "clsx";

export function cn(...inputs: ClassValue[]): string {
  return clsx(inputs);
}

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\\w\\s-]/g, "")
    .replace(/[\\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function formatPhone(phone: string): string {
  const cleaned = phone.replace(/\\D/g, "");
  if (cleaned.length === 10) {
    return \`(\${cleaned.slice(0, 3)}) \${cleaned.slice(3, 6)}-\${cleaned.slice(6)}\`;
  }
  return phone;
}

export function formatPhoneLink(phone: string): string {
  const cleaned = phone.replace(/\\D/g, "");
  return \`+1\${cleaned}\`;
}

export function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength - 3) + "...";
}
`;

  return {
    path: 'src/lib/utils.ts',
    content,
    type: 'data',
    generator: 'template',
    size: 0,
  };
}
